services:
  api:
    build: 
      context: ./backend
      dockerfile: Dockerfile.api
      args:
        - BASE_IMAGE=agentic-doc-base-local:latest
    image: agentic-doc-api-local:v1.5.0
    ports:
      - "8000:8000"
    environment:
      - CLOUD_PROVIDER=aws
      - RUNTIME_MODE=aws
      - PROCESSING_MODE=async
      - QUEUE_PROVIDER=sqs
      - STORAGE_PROVIDER=s3
      - AGENT_PROVIDER=python_orchestrated
      - KNOWLEDGE_PROVIDER=bedrock_kb
      - LLM_BACKEND=aws_bedrock
      - AWS_REGION=${AWS_REGION:-ap-south-1}
      - AWS_PROFILE=default
      - S3_BUCKET_INPUT=${S3_BUCKET_INPUT}
      - S3_BUCKET_OUTPUT=${S3_BUCKET_OUTPUT}
      - SQS_PROCESSING_QUEUE_URL=${SQS_PROCESSING_QUEUE_URL}
      - DATABASE_URL=${DATABASE_URL}
      - BEDROCK_AGENT_ID=${BEDROCK_AGENT_ID}
      - BEDROCK_AGENT_ALIAS_ID=${BEDROCK_AGENT_ALIAS_ID}
      - BEDROCK_KB_ID=${BEDROCK_KB_ID}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
#      - AWS_BEARER_TOKEN_BEDROCK=${AWS_BEARER_TOKEN_BEDROCK}
    volumes:
      - ~/.aws:/root/.aws
      - ./backend/app:/app/app
      - ./backend/scripts:/app/scripts

  worker:
    build: 
      context: ./backend
      dockerfile: Dockerfile.worker
      args:
        - BASE_IMAGE=agentic-doc-base-local:latest
    image: agentic-doc-worker-local:v1.5.0
    environment:
      - CLOUD_PROVIDER=aws
      - RUNTIME_MODE=aws
      - PROCESSING_MODE=async
      - QUEUE_PROVIDER=sqs
      - STORAGE_PROVIDER=s3
      - AGENT_PROVIDER=python_orchestrated
      - KNOWLEDGE_PROVIDER=bedrock_kb
      - LLM_BACKEND=aws_bedrock
      - AWS_REGION=${AWS_REGION:-ap-south-1}
      - AWS_PROFILE=default
      - S3_BUCKET_INPUT=${S3_BUCKET_INPUT}
      - S3_BUCKET_OUTPUT=${S3_BUCKET_OUTPUT}
      - SQS_PROCESSING_QUEUE_URL=${SQS_PROCESSING_QUEUE_URL}
      - DATABASE_URL=${DATABASE_URL}
      - BEDROCK_AGENT_ID=${BEDROCK_AGENT_ID}
      - BEDROCK_AGENT_ALIAS_ID=${BEDROCK_AGENT_ALIAS_ID}
      - BEDROCK_KB_ID=${BEDROCK_KB_ID}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
#      - AWS_BEARER_TOKEN_BEDROCK=${AWS_BEARER_TOKEN_BEDROCK}
    volumes:
      - ~/.aws:/root/.aws

  frontend:
    build: 
      context: ./frontend
      args:
        - ENVIRONMENT=development
    image: agentic-doc-frontend-local:v1.2.4
    ports:
      - "4200:80"
    depends_on:
      - api
