from abc import ABC, abstractmethod
from typing import Any, Dict

class LlmRuntimeAdapter(ABC):
    """
    Abstract Base Class for LLM Runtimes.
    Ensures that business logic (like agents) remains cloud-agnostic.
    """

    @abstractmethod
    def generate(
        self,
        prompt: str,
        *,
        system_prompt: str | None = None,
        response_format: dict | None = None,
        temperature: float = 0.1,
        max_tokens: int | None = None,
        **kwargs
    ) -> str:
        """
        Generate text completion based on a prompt.

        Args:
            prompt: The instruction or query to evaluate.
            system_prompt: Optional system prompt to steer the model.
            response_format: Optional schema hints for structured generation.
            temperature: The sampling temperature.
            max_tokens: Maximum number of tokens to generate.
            **kwargs: Additional provider-specific configuration overrides.

        Returns:
            The raw text response generated by the LLM.
        """
        pass
