from abc import ABC, abstractmethod
from typing import Any, Dict

class LlmRuntimeAdapter(ABC):
    """
    Abstract Base Class for LLM Runtimes.
    Ensures that business logic (like agents) remains cloud-agnostic.
    """

    @abstractmethod
    def generate(self, prompt: str, **kwargs) -> str:
        """
        Generate text completion based on a prompt.

        Args:
            prompt: The instruction or query to evaluate.
            **kwargs: Additional provider-specific configuration overrides (e.g. temperature).

        Returns:
            The raw text response generated by the LLM.
        """
        pass
